name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听主分支的变更

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 使用 Node.js 版本

    - name: Install dependencies
      run: npm install
      working-directory: ./vue  # Update this path to where your package.json is located

    - name: Build project
      run: npm run build  # 假设你的构建命令是 `npm run build`
      working-directory: ./vue  # Ensure this matches the path above

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./vue/dist  # Update this path if necessary
        destination_branch: gh-pages  # 部署到 `gh-pages` 分支
